### ISSUE TITLE
【確認待ち】翻訳作業@公式

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vk-google-job-posting-manager#32]
WordPress アカウントにログインして下記から作業する
https://translate.wordpress.org/projects/wp-plugins/vk-google-job-posting-manager/

**Comment by drill-lancer** [comment]
@kurudrive 
自分なりに翻訳を当てて見たので確認お願いします。
https://translate.wordpress.org/projects/wp-plugins/vk-google-job-posting-manager/

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました。
以下 AUTOMATTICの直子さんから

@kurudrive さんと、DRILL LANCER (rickaddison7634) さんに PTE 権限追加しましたー。
全体的にとてもきっちり翻訳していただいていたのですが、以下だけ、私の方で修正しておきました。主に句点がピリオドの有無と一致していなかったりとか、細かいタイポとかです。参考になりましたら :woman-bowing:
https://translate.wordpress.org/projects/wp-plugins/vk-google-job-posting-manager/stable[…]er=Apply+Filters&sort%5Bby%5D=original&sort%5Bhow%5D=desc
