### ISSUE TITLE
Syntax Error Preventing Plugin Activation

### ISSUE THREAD

**Issue by jjonesdesign** [vektor-inc/vk-google-job-posting-manager#33]
File: vk-google-job-posting-manager/blocks/vk-google-job-posting-manager-block.php
Line: 27
Issue: Unnecessary comma "," at end of line causing php syntax error
Solution: Remove extra comma ","

I tried to submit a change request, but do not have permission to submit them :)

Thanks.

**Comment by kurudrive** [comment]
@jjonesdesign Hi. Thanks your report!!

I fixed and release 1.2.1 !!
