### ISSUE TITLE
WP最新版で多分ブロックが表示されない

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-google-job-posting-manager#61]
そもそもたぶん 6.6 ではブロックが表示されなくなってると思うので要修正

https://vws.vektor-inc.co.jp/forums/topic/100181

---

2023年度ベクトル有償製品ユーザーアンケートにて、
VK Google Job Posting Manager ご活用の方から最新版WPでのテスト要望がありましたのでお知らせしておきます🙏

> This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

https://wordpress.org/plugins/vk-google-job-posting-manager/

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございましたたたたーん！
