### ISSUE TITLE
オプション値の global $prefix; について

### ISSUE THREAD

**Issue by munyagu** [vektor-inc/vk-google-job-posting-manager#9]
私が使っている、本当にイケていないテーマが
`global $prefix;`
を使っていまして、そのテーマが`$prefix`を上書きしてしまい、0.5.2にアップデートすると設定値が全て消えてしまいました。

このままですと、他テーマに変更すると再度設定した値も消えてしまいます。
`$prefix`という一般的な名称のグローバル変数名に何らかのプレフィックスをつけて頂くか、何かのクラスのスタティックメンバーなどに変更していただけないものでしょうか。

**Comment by munyagu** [comment]
すいません、「全て」、ではないですね、「一部」、の誤りです。

**Comment by kurudrive** [comment]
あぁぁぁぁぁ、なるほど...ありえますね...。

@naogify よろしくデス（・ｗ・

**Comment by kurudrive** [comment]
本件対応済みにつきcloseしますー。
